[package]
name = "crud"
version = "0.1.5"
authors = ["Andrew <debiannuser@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hesoyam = { path = "../../hesoyam" }

chrono = "0.4.13"
